# Generated by Django 3.2.3 on 2021-05-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profiles_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='account_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
